name: Nix Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Run Nix Build
      run: nix build
    - run: test -x result/bin/radmin-vpn-linux
    - run: test -f result/share/radmin-vpn-linux/build/rvpnnetmp.sys
